/**
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY ⚠️
 *
 * This file is auto-generated by running:
 *   npx tsx scripts/generate-size-edges.ts
 *
 * Hardcoded product sizes, layouts, and sets data for each board type.
 * These values are static (board configurations don't change) so we hardcode them
 * to eliminate database queries.
 *
 * Generated at: 2025-12-28T00:35:58.397Z
 */

import { BoardName } from '@/app/lib/types';

export interface ProductSizeData {
  id: number;
  name: string;
  description: string;
  edgeLeft: number;
  edgeRight: number;
  edgeBottom: number;
  edgeTop: number;
  productId: number;
}

export interface LayoutData {
  id: number;
  name: string;
  productId: number;
}

export interface SetData {
  id: number;
  name: string;
}

export interface SizeEdges {
  edgeLeft: number;
  edgeRight: number;
  edgeBottom: number;
  edgeTop: number;
}

export const PRODUCT_SIZES: Record<BoardName, Record<number, ProductSizeData>> = {
  kilter: {
    7: { id: 7, name: '12 x 14', description: 'Commerical', edgeLeft: 0, edgeRight: 144, edgeBottom: 0, edgeTop: 180, productId: 1 },
    8: { id: 8, name: '8 x 12', description: 'Home', edgeLeft: 24, edgeRight: 120, edgeBottom: 0, edgeTop: 156, productId: 1 },
    10: { id: 10, name: '12 x 12 with kickboard', description: 'Square', edgeLeft: 0, edgeRight: 144, edgeBottom: 0, edgeTop: 156, productId: 1 },
    11: { id: 11, name: 'Full Wall', description: '', edgeLeft: 0, edgeRight: 210, edgeBottom: 0, edgeTop: 116, productId: 2 },
    12: { id: 12, name: '5 Holds', description: '4 bolt-ons + 1 screw-on', edgeLeft: -8, edgeRight: 8, edgeBottom: 0, edgeTop: 16, productId: 3 },
    13: { id: 13, name: '10 x 10', description: '', edgeLeft: -60, edgeRight: 60, edgeBottom: -12, edgeTop: 120, productId: 4 },
    14: { id: 14, name: '7 x 10', description: 'Small', edgeLeft: 28, edgeRight: 116, edgeBottom: 36, edgeTop: 156, productId: 1 },
    15: { id: 15, name: 'Spire', description: '', edgeLeft: 0, edgeRight: 128, edgeBottom: -16, edgeTop: 280, productId: 5 },
    16: { id: 16, name: 'Full', description: '', edgeLeft: 0, edgeRight: 198, edgeBottom: 0, edgeTop: 300, productId: 6 },
    17: { id: 17, name: '7x10', description: 'Full Ride LED Kit', edgeLeft: -44, edgeRight: 44, edgeBottom: 24, edgeTop: 144, productId: 7 },
    18: { id: 18, name: '7x10', description: 'Mainline LED Kit', edgeLeft: -44, edgeRight: 44, edgeBottom: 24, edgeTop: 144, productId: 7 },
    19: { id: 19, name: '7x10', description: 'Auxiliary LED Kit', edgeLeft: -44, edgeRight: 44, edgeBottom: 24, edgeTop: 144, productId: 7 },
    20: { id: 20, name: '10 x 12', description: '', edgeLeft: -60, edgeRight: 60, edgeBottom: -12, edgeTop: 144, productId: 4 },
    21: { id: 21, name: '10x10', description: 'Full Ride LED Kit', edgeLeft: -56, edgeRight: 56, edgeBottom: 24, edgeTop: 144, productId: 7 },
    22: { id: 22, name: '10x10', description: 'Mainline LED Kit', edgeLeft: -56, edgeRight: 56, edgeBottom: 24, edgeTop: 144, productId: 7 },
    23: { id: 23, name: '8x12', description: 'Full Ride LED Kit', edgeLeft: -44, edgeRight: 44, edgeBottom: -12, edgeTop: 144, productId: 7 },
    24: { id: 24, name: '8x12', description: 'Mainline LED Kit', edgeLeft: -44, edgeRight: 44, edgeBottom: -12, edgeTop: 144, productId: 7 },
    25: { id: 25, name: '10x12', description: 'Full Ride LED Kit', edgeLeft: -56, edgeRight: 56, edgeBottom: -12, edgeTop: 144, productId: 7 },
    26: { id: 26, name: '10x12', description: 'Mainline LED Kit', edgeLeft: -56, edgeRight: 56, edgeBottom: -12, edgeTop: 144, productId: 7 },
    27: { id: 27, name: '12 x 12 without kickboard', description: 'Square', edgeLeft: 0, edgeRight: 144, edgeBottom: 12, edgeTop: 156, productId: 1 },
    28: { id: 28, name: '16 x 12', description: 'Super Wide', edgeLeft: -24, edgeRight: 168, edgeBottom: 0, edgeTop: 156, productId: 1 },
    29: { id: 29, name: '10x10', description: 'Auxiliary LED Kit', edgeLeft: -56, edgeRight: 56, edgeBottom: 24, edgeTop: 144, productId: 7 },
  },
  tension: {
    1: { id: 1, name: 'Full Wall', description: 'Rows: KB1, KB2, 1-18 Columns: A-K', edgeLeft: 0, edgeRight: 96, edgeBottom: 0, edgeTop: 156, productId: 4 },
    2: { id: 2, name: 'Half Kickboard', description: 'Rows: KB2, 1-18 Columns: A-K', edgeLeft: 0, edgeRight: 96, edgeBottom: 4, edgeTop: 156, productId: 4 },
    3: { id: 3, name: 'No Kickboard', description: 'Rows: 1-18 Columns: A-K', edgeLeft: 0, edgeRight: 96, edgeBottom: 8, edgeTop: 156, productId: 4 },
    4: { id: 4, name: 'Short', description: 'Rows: 1-15 Columns: A-K', edgeLeft: 0, edgeRight: 96, edgeBottom: 8, edgeTop: 132, productId: 4 },
    5: { id: 5, name: 'Short & Narrow', description: 'Rows: 1-15 Columns: B.5-I.5', edgeLeft: 16, edgeRight: 80, edgeBottom: 8, edgeTop: 132, productId: 4 },
    6: { id: 6, name: '12 high x 12 wide', description: '', edgeLeft: -68, edgeRight: 68, edgeBottom: 0, edgeTop: 144, productId: 5 },
    7: { id: 7, name: '10 high x 12 wide', description: '', edgeLeft: -68, edgeRight: 68, edgeBottom: 0, edgeTop: 120, productId: 5 },
    8: { id: 8, name: '12 high x 8 wide', description: '', edgeLeft: -44, edgeRight: 44, edgeBottom: 0, edgeTop: 144, productId: 5 },
    9: { id: 9, name: '10 high x 8 wide', description: '', edgeLeft: -44, edgeRight: 44, edgeBottom: 0, edgeTop: 120, productId: 5 },
  },
};

export const LAYOUTS: Record<BoardName, Record<number, LayoutData>> = {
  kilter: {
    1: { id: 1, name: 'Kilter Board Original', productId: 1 },
    8: { id: 8, name: 'Kilter Board Homewall', productId: 7 },
  },
  tension: {
    9: { id: 9, name: 'Original Layout', productId: 4 },
    10: { id: 10, name: 'Tension Board 2 Mirror', productId: 5 },
    11: { id: 11, name: 'Tension Board 2 Spray', productId: 5 },
  },
};

// Sets indexed by "layoutId-sizeId" key
export const SETS: Record<BoardName, Record<string, SetData[]>> = {
  kilter: {
    '1-7': [{ id: 1, name: 'Bolt Ons' }, { id: 20, name: 'Screw Ons' }],
    '1-8': [{ id: 1, name: 'Bolt Ons' }, { id: 20, name: 'Screw Ons' }],
    '1-10': [{ id: 1, name: 'Bolt Ons' }, { id: 20, name: 'Screw Ons' }],
    '1-14': [{ id: 1, name: 'Bolt Ons' }, { id: 20, name: 'Screw Ons' }],
    '1-27': [{ id: 1, name: 'Bolt Ons' }, { id: 20, name: 'Screw Ons' }],
    '1-28': [{ id: 1, name: 'Bolt Ons' }, { id: 20, name: 'Screw Ons' }],
    '2-11': [{ id: 21, name: 'JUUL All' }],
    '3-12': [{ id: 22, name: 'Demo Holds' }],
    '4-13': [{ id: 23, name: 'BKB All' }],
    '4-20': [{ id: 23, name: 'BKB All' }],
    '5-15': [{ id: 24, name: 'Spire All' }],
    '6-16': [{ id: 25, name: 'Orbit' }],
    '7-16': [{ id: 25, name: 'Orbit' }],
    '8-17': [{ id: 26, name: 'Mainline' }, { id: 27, name: 'Auxiliary' }],
    '8-18': [{ id: 26, name: 'Mainline' }],
    '8-19': [{ id: 27, name: 'Auxiliary' }],
    '8-21': [{ id: 26, name: 'Mainline' }, { id: 27, name: 'Auxiliary' }],
    '8-22': [{ id: 26, name: 'Mainline' }],
    '8-23': [{ id: 26, name: 'Mainline' }, { id: 27, name: 'Auxiliary' }, { id: 28, name: 'Mainline Kickboard' }, { id: 29, name: 'Auxiliary Kickboard' }],
    '8-24': [{ id: 26, name: 'Mainline' }, { id: 28, name: 'Mainline Kickboard' }, { id: 29, name: 'Auxiliary Kickboard' }],
    '8-25': [{ id: 26, name: 'Mainline' }, { id: 27, name: 'Auxiliary' }, { id: 28, name: 'Mainline Kickboard' }, { id: 29, name: 'Auxiliary Kickboard' }],
    '8-26': [{ id: 26, name: 'Mainline' }, { id: 28, name: 'Mainline Kickboard' }, { id: 29, name: 'Auxiliary Kickboard' }],
    '8-29': [{ id: 27, name: 'Auxiliary' }],
  },
  tension: {
    '9-1': [{ id: 8, name: 'Set A' }, { id: 9, name: 'Set B' }, { id: 10, name: 'Set C' }, { id: 11, name: 'Foot Set' }],
    '9-2': [{ id: 8, name: 'Set A' }, { id: 9, name: 'Set B' }, { id: 10, name: 'Set C' }, { id: 11, name: 'Foot Set' }],
    '9-3': [{ id: 8, name: 'Set A' }, { id: 9, name: 'Set B' }, { id: 10, name: 'Set C' }, { id: 11, name: 'Foot Set' }],
    '9-4': [{ id: 8, name: 'Set A' }, { id: 9, name: 'Set B' }, { id: 10, name: 'Set C' }, { id: 11, name: 'Foot Set' }],
    '9-5': [{ id: 8, name: 'Set A' }, { id: 9, name: 'Set B' }, { id: 10, name: 'Set C' }, { id: 11, name: 'Foot Set' }],
    '10-6': [{ id: 12, name: 'Wood' }, { id: 13, name: 'Plastic' }],
    '10-7': [{ id: 12, name: 'Wood' }, { id: 13, name: 'Plastic' }],
    '10-8': [{ id: 12, name: 'Wood' }, { id: 13, name: 'Plastic' }],
    '10-9': [{ id: 12, name: 'Wood' }, { id: 13, name: 'Plastic' }],
    '11-6': [{ id: 12, name: 'Wood' }, { id: 13, name: 'Plastic' }],
    '11-7': [{ id: 12, name: 'Wood' }, { id: 13, name: 'Plastic' }],
    '11-8': [{ id: 12, name: 'Wood' }, { id: 13, name: 'Plastic' }],
    '11-9': [{ id: 12, name: 'Wood' }, { id: 13, name: 'Plastic' }],
  },
};

/**
 * Get size edges for a given board and size ID.
 * Returns null if the size ID is not found.
 */
export const getSizeEdges = (boardName: BoardName, sizeId: number): SizeEdges | null => {
  const size = PRODUCT_SIZES[boardName]?.[sizeId];
  if (!size) return null;
  return {
    edgeLeft: size.edgeLeft,
    edgeRight: size.edgeRight,
    edgeBottom: size.edgeBottom,
    edgeTop: size.edgeTop,
  };
};

/**
 * Get full product size data for a given board and size ID.
 * Returns null if the size ID is not found.
 */
export const getProductSize = (boardName: BoardName, sizeId: number): ProductSizeData | null => {
  return PRODUCT_SIZES[boardName]?.[sizeId] ?? null;
};

/**
 * Get layout data for a given board and layout ID.
 * Returns null if the layout ID is not found.
 */
export const getLayout = (boardName: BoardName, layoutId: number): LayoutData | null => {
  return LAYOUTS[boardName]?.[layoutId] ?? null;
};

/**
 * Get all layouts for a given board.
 */
export const getAllLayouts = (boardName: BoardName): LayoutData[] => {
  const layouts = LAYOUTS[boardName];
  if (!layouts) return [];
  return Object.values(layouts);
};

/**
 * Get all sizes for a given board and layout ID.
 * Uses the layout's product_id to find matching sizes.
 */
export const getSizesForLayoutId = (boardName: BoardName, layoutId: number): ProductSizeData[] => {
  const layout = LAYOUTS[boardName]?.[layoutId];
  if (!layout) return [];
  const sizes = PRODUCT_SIZES[boardName];
  if (!sizes) return [];
  return Object.values(sizes).filter(size => size.productId === layout.productId);
};

/**
 * Get all sizes for a given board and product ID.
 * Used by the board selector to list available sizes.
 */
export const getSizesForProduct = (boardName: BoardName, productId: number): ProductSizeData[] => {
  const sizes = PRODUCT_SIZES[boardName];
  if (!sizes) return [];
  return Object.values(sizes).filter(size => size.productId === productId);
};

/**
 * Get all sets for a given board, layout, and size.
 */
export const getSetsForLayoutAndSize = (boardName: BoardName, layoutId: number, sizeId: number): SetData[] => {
  const key = `${layoutId}-${sizeId}`;
  return SETS[boardName]?.[key] ?? [];
};

/**
 * Default size IDs for each layout.
 * Used by the setup wizard to pre-select a sensible default.
 */
export const DEFAULT_SIZE_FOR_LAYOUT: Record<BoardName, Record<number, number>> = {
  kilter: {
    1: 10,  // Kilter Board Original -> 12 x 12 with kickboard
    8: 17,  // Kilter Board Homewall -> 7x10 Full Ride LED Kit
  },
  tension: {
    9: 1,   // Original Layout -> Full Wall (first size is fine)
    10: 8,  // Tension Board 2 Mirror -> 12 high x 8 wide
    11: 8,  // Tension Board 2 Spray -> 12 high x 8 wide
  },
};

/**
 * Get the default size ID for a given board and layout.
 * Falls back to the first available size if no default is defined.
 */
export const getDefaultSizeForLayout = (boardName: BoardName, layoutId: number): number | null => {
  const defaultSizeId = DEFAULT_SIZE_FOR_LAYOUT[boardName]?.[layoutId];
  if (defaultSizeId !== undefined) {
    return defaultSizeId;
  }
  // Fall back to first available size
  const sizes = getSizesForLayoutId(boardName, layoutId);
  return sizes.length > 0 ? sizes[0].id : null;
};

/**
 * Get all board selector options (layouts, sizes, sets) from hardcoded data.
 * This replaces the database query in getAllBoardSelectorOptions.
 */
export const getBoardSelectorOptions = () => {
  const boardNames: BoardName[] = ['kilter', 'tension'];

  const layouts: Record<BoardName, { id: number; name: string }[]> = {} as Record<BoardName, { id: number; name: string }[]>;
  const sizes: Record<string, { id: number; name: string; description: string }[]> = {};
  const sets: Record<string, { id: number; name: string }[]> = {};

  for (const boardName of boardNames) {
    // Get layouts
    layouts[boardName] = getAllLayouts(boardName).map(l => ({ id: l.id, name: l.name }));

    // Get sizes for each layout
    for (const layout of layouts[boardName]) {
      const layoutSizes = getSizesForLayoutId(boardName, layout.id);
      const sizeKey = `${boardName}-${layout.id}`;
      sizes[sizeKey] = layoutSizes.map(s => ({ id: s.id, name: s.name, description: s.description }));

      // Get sets for each size
      for (const size of layoutSizes) {
        const setKey = `${boardName}-${layout.id}-${size.id}`;
        sets[setKey] = getSetsForLayoutAndSize(boardName, layout.id, size.id);
      }
    }
  }

  return { layouts, sizes, sets };
};
