/**
 * Hardcoded size edge values for each board type.
 * These values are static (board dimensions don't change) so we hardcode them
 * to eliminate a database query on every search request.
 *
 * Generated by: npx tsx scripts/generate-size-edges.ts
 * Generated at: 2025-12-27
 */

import { BoardName } from '@/app/lib/types';

export interface SizeEdges {
  edgeLeft: number;
  edgeRight: number;
  edgeBottom: number;
  edgeTop: number;
}

export const SIZE_EDGES: Record<BoardName, Record<number, SizeEdges>> = {
  kilter: {
    7: { edgeLeft: 0, edgeRight: 144, edgeBottom: 0, edgeTop: 180 }, // 12 x 14
    8: { edgeLeft: 24, edgeRight: 120, edgeBottom: 0, edgeTop: 156 }, // 8 x 12
    10: { edgeLeft: 0, edgeRight: 144, edgeBottom: 0, edgeTop: 156 }, // 12 x 12 with kickboard
    11: { edgeLeft: 0, edgeRight: 210, edgeBottom: 0, edgeTop: 116 }, // Full Wall
    12: { edgeLeft: -8, edgeRight: 8, edgeBottom: 0, edgeTop: 16 }, // 5 Holds
    13: { edgeLeft: -60, edgeRight: 60, edgeBottom: -12, edgeTop: 120 }, // 10 x 10
    14: { edgeLeft: 28, edgeRight: 116, edgeBottom: 36, edgeTop: 156 }, // 7 x 10
    15: { edgeLeft: 0, edgeRight: 128, edgeBottom: -16, edgeTop: 280 }, // Spire
    16: { edgeLeft: 0, edgeRight: 198, edgeBottom: 0, edgeTop: 300 }, // Full
    17: { edgeLeft: -44, edgeRight: 44, edgeBottom: 24, edgeTop: 144 }, // 7x10
    18: { edgeLeft: -44, edgeRight: 44, edgeBottom: 24, edgeTop: 144 }, // 7x10
    19: { edgeLeft: -44, edgeRight: 44, edgeBottom: 24, edgeTop: 144 }, // 7x10
    20: { edgeLeft: -60, edgeRight: 60, edgeBottom: -12, edgeTop: 144 }, // 10 x 12
    21: { edgeLeft: -56, edgeRight: 56, edgeBottom: 24, edgeTop: 144 }, // 10x10
    22: { edgeLeft: -56, edgeRight: 56, edgeBottom: 24, edgeTop: 144 }, // 10x10
    23: { edgeLeft: -44, edgeRight: 44, edgeBottom: -12, edgeTop: 144 }, // 8x12
    24: { edgeLeft: -44, edgeRight: 44, edgeBottom: -12, edgeTop: 144 }, // 8x12
    25: { edgeLeft: -56, edgeRight: 56, edgeBottom: -12, edgeTop: 144 }, // 10x12
    26: { edgeLeft: -56, edgeRight: 56, edgeBottom: -12, edgeTop: 144 }, // 10x12
    27: { edgeLeft: 0, edgeRight: 144, edgeBottom: 12, edgeTop: 156 }, // 12 x 12 without kickboard
    28: { edgeLeft: -24, edgeRight: 168, edgeBottom: 0, edgeTop: 156 }, // 16 x 12
    29: { edgeLeft: -56, edgeRight: 56, edgeBottom: 24, edgeTop: 144 }, // 10x10
  },
  tension: {
    1: { edgeLeft: 0, edgeRight: 96, edgeBottom: 0, edgeTop: 156 }, // Full Wall
    2: { edgeLeft: 0, edgeRight: 96, edgeBottom: 4, edgeTop: 156 }, // Half Kickboard
    3: { edgeLeft: 0, edgeRight: 96, edgeBottom: 8, edgeTop: 156 }, // No Kickboard
    4: { edgeLeft: 0, edgeRight: 96, edgeBottom: 8, edgeTop: 132 }, // Short
    5: { edgeLeft: 16, edgeRight: 80, edgeBottom: 8, edgeTop: 132 }, // Short & Narrow
    6: { edgeLeft: -68, edgeRight: 68, edgeBottom: 0, edgeTop: 144 }, // 12 high x 12 wide
    7: { edgeLeft: -68, edgeRight: 68, edgeBottom: 0, edgeTop: 120 }, // 10 high x 12 wide
    8: { edgeLeft: -44, edgeRight: 44, edgeBottom: 0, edgeTop: 144 }, // 12 high x 8 wide
    9: { edgeLeft: -44, edgeRight: 44, edgeBottom: 0, edgeTop: 120 }, // 10 high x 8 wide
  },
};

/**
 * Get size edges for a given board and size ID.
 * Returns null if the size ID is not found.
 */
export const getSizeEdges = (boardName: BoardName, sizeId: number): SizeEdges | null => {
  return SIZE_EDGES[boardName]?.[sizeId] ?? null;
};
