/**
 * Script to generate the SIZE_EDGES constant from the database.
 *
 * Usage:
 *   cd packages/web
 *   docker-compose -f db/docker-compose.yml up -d
 *   npx tsx scripts/generate-size-edges.ts
 *
 * This outputs TypeScript code that can be copied into size-edges.ts
 */

import { execSync } from 'child_process';

interface SizeEdge {
  id: number;
  name: string;
  edge_left: number;
  edge_right: number;
  edge_bottom: number;
  edge_top: number;
}

function queryDatabase(table: string): SizeEdge[] {
  const result = execSync(
    `docker exec db-postgres-1 psql -U postgres -d main -t -A -F ',' -c "SELECT id, name, edge_left, edge_right, edge_bottom, edge_top FROM ${table} ORDER BY id;"`,
    { encoding: 'utf-8' }
  );

  return result
    .trim()
    .split('\n')
    .filter(line => line.length > 0)
    .map(line => {
      const [id, name, edge_left, edge_right, edge_bottom, edge_top] = line.split(',');
      return {
        id: parseInt(id),
        name,
        edge_left: parseInt(edge_left),
        edge_right: parseInt(edge_right),
        edge_bottom: parseInt(edge_bottom),
        edge_top: parseInt(edge_top),
      };
    });
}

function generateTypeScript(boardName: string, sizes: SizeEdge[]): string {
  const entries = sizes.map(s =>
    `    ${s.id}: { edgeLeft: ${s.edge_left}, edgeRight: ${s.edge_right}, edgeBottom: ${s.edge_bottom}, edgeTop: ${s.edge_top} }, // ${s.name}`
  ).join('\n');

  return `  ${boardName}: {\n${entries}\n  }`;
}

async function main() {
  console.log('Querying kilter_product_sizes...');
  const kilterSizes = queryDatabase('kilter_product_sizes');

  console.log('Querying tension_product_sizes...');
  const tensionSizes = queryDatabase('tension_product_sizes');

  const output = `/**
 * Hardcoded size edge values for each board type.
 * These values are static (board dimensions don't change) so we hardcode them
 * to eliminate a database query on every search request.
 *
 * Generated by: npx tsx scripts/generate-size-edges.ts
 * Generated at: ${new Date().toISOString()}
 */

import { BoardName } from '@/app/lib/types';

export interface SizeEdges {
  edgeLeft: number;
  edgeRight: number;
  edgeBottom: number;
  edgeTop: number;
}

export const SIZE_EDGES: Record<BoardName, Record<number, SizeEdges>> = {
${generateTypeScript('kilter', kilterSizes)},
${generateTypeScript('tension', tensionSizes)},
};

/**
 * Get size edges for a given board and size ID.
 * Returns null if the size ID is not found.
 */
export const getSizeEdges = (boardName: BoardName, sizeId: number): SizeEdges | null => {
  return SIZE_EDGES[boardName]?.[sizeId] ?? null;
};
`;

  console.log('\n// ====== Generated Code ======\n');
  console.log(output);
}

main().catch(console.error);
